// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jppqdvkvuzitsbtfotgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwcHFkdmt2dXppdHNidGZvdGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDQ4MDYsImV4cCI6MjA2NzI4MDgwNn0.MI26t5aYLnV7emDuDJKs_SlrRqCUQoqqAWf_ZFhN9DA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});